//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.22 at 01:03:02 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://fundevelopment.com/producing-web-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fundevelopment.producing_web_service;
